name: Practice 1
on: workflow_dispatch
jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: cache dependencies
         uses: actions/cache@v3
         with:
            path: ~/.npm
            key: CACHE_KEY_${{hashFiles('**/package-lock.json')}}
            
       - name: pull dependencies
         run: npm ci
       - name: run lint
         run: npm run lint  

   