name: Practice 1
on: push
jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: pull dependencies
         uses: npm ci
       - name: run lint
         uses: npm run lint  

   