name: Practice 1
on: push
jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: pull dependencies
         run: npm ci
       - name: run lint
         run: npm lint  

   